In [7]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1
print(arr)
# Створіть та перетворіть 1D-масив на 2D-масив із 2 рядками

arr_1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr = arr_1.reshape(2, -1)
print(arr_1)
# Створіть два двовимірні масиви а і b, та складіть масиви їх вертикально

a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])
c = np.vstack((a, b))
print(c)
# Створіть наступний шаблон без жорсткого кодування(Hard coding) . Використовуйте лише функції Numpy і наведений нижче масив введення

a = np.array([1,2,3])
a = np.tile(a, 3)
print(a)
# Отримайте спільні елементи між a і b

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
common_elements = np.intersect1d(a, b)
print(common_elements)
# Отримайте позиції перших 5 максимальних значень у заданому масиві a

np.random.seed(100)
a = np.random.uniform(1,50, 20)
indices = np.argpartition(a, -5)[-5:]
print(indices[np.argsort(a[indices])[::-1]])
# Вилучіть усі значення NaN із одновимірного масиву

a = np.array([1,2,3,np.nan,5,6,7,np.nan])
a = a[np.isnan(a)]
print(a_1)
# Обчисліть евклідову відстань між двома масивами a і b.

a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
distance = np.linalg.norm(a - b)
print(distance)
# Знайдіть індекс 5-го повторення числа 1 у масиві x

x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
indices = np.where(x == 1)[0]
if len(indices) >= 5:
    fifth_index = indices[4]
else:
    fifth_index = -1
print(fifth_index)
# Знайдіть повторювані записи (від 2-го випадку повторення і далі) у заданому масиві і позначте їх як True. Перше повторення має бути False.

np.random.seed(100)
a = np.random.randint(0, 5, 10)
a = np.where(a[:-1] == a[1:], True, False)[0]
print(a_2)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[1 2 3 1 2 3 1 2 3]
[2 4]
[15 10  3  7 18]
[ 1.  2.  3. nan  5.  6.  7. nan]
6.708203932499369
8
True
