In [1]:
import numpy as np

vector1 = np.arange(1, 11)
print("Одновимірний масив з першими 10-ма натуральними числами:")
print(vector1)

matrix1 = np.zeros((3, 3))
print("\nДвовимірний масив розміром 3x3, заповнений нулями:")
print(matrix1)

matrix2 = np.random.randint(1, 11, (5, 5))
print("\nМасив розміром 5x5, заповнений випадковими цілими числами в діапазоні від 1 до 10:")
print(matrix2)

matrix3 = np.random.rand(4, 4)
print("\nМасив розміром 4x4, заповнений випадковими дійсними числами в діапазоні від 0 до 1:")
print(matrix3)

vector2 = np.random.randint(1, 11, 5)
vector3 = np.random.randint(1, 11, 5)

addition = vector2 + vector3
subtraction = vector2 - vector3
multiplication = vector2 * vector3
print("\nДодавання:", addition)
print("Віднімання:", subtraction)
print("Множення:", multiplication)

vector4 = np.random.randint(1, 11, 7)
vector5 = np.random.randint(1, 11, 7)

dot_product = np.dot(vector4, vector5)
print("\nСкалярний добуток двох векторів:", dot_product)

matrix4 = np.random.randint(1, 11, (2, 2))
matrix5 = np.random.randint(1, 11, (2, 3))

matrix_multiply = np.dot(matrix4, matrix5)
print("\nРезультат множення двох матриць:")
print(matrix_multiply)

matrix6 = np.random.randint(1, 11, (3, 3))

inverse_matrix = np.linalg.inv(matrix6)
print("\nОбернена матриця:")
print(inverse_matrix)

matrix7 = np.random.rand(4, 4)

transposed_matrix = np.transpose(matrix7)
print("\nТранспонована матриця:")
print(transposed_matrix)

matrix8 = np.random.randint(1, 11, (3, 4))
vector6 = np.random.randint(1, 11, 4)

matrix_vector_product = np.dot(matrix8, vector6)
print("\nРезультат множення матриці на вектор:")
print(matrix_vector_product)

matrix9 = np.random.rand(2, 3)
vector7 = np.random.rand(3)

# Перемножте матрицю на вектор
matrix_vector_product2 = np.dot(matrix9, vector7)
print("\nРезультат множення матриці на вектор:")
print(matrix_vector_product2)

matrix1 = np.random.randint(1, 11, (2, 2))
matrix2 = np.random.randint(1, 11, (2, 2))

matrix_product = np.dot(matrix1, matrix2)
print("Добуток двох матриць:")
print(matrix_product)

matrix3 = np.random.randint(1, 101, (5, 5))

# Знайдіть суму елементів матриці
matrix_sum = np.sum(matrix3)
print("\nСума елементів матриці:")
print(matrix_sum)

matrix4 = np.random.randint(1, 11, (4, 4))
matrix5 = np.random.randint(1, 11, (4, 4))

matrix_difference = matrix4 - matrix5
print("\nРізниця двох матриць:")
print(matrix_difference)

matrix6 = np.random.rand(3, 3)

row_sums = np.sum(matrix6, axis=1)
column_vector = row_sums.reshape(-1, 1)
print("\nВектор-стовпчик з сумами елементів кожного рядка матриці:")
print(column_vector)

matrix7 = np.random.randint(1, 11, (3, 4))

squared_matrix = np.square(matrix7)
print("\nМатриця з квадратами чисел:")
print(squared_matrix)

vector = np.random.randint(1, 51, 4)

square_root_vector = np.sqrt(vector)
print("\nВектор з квадратними коренями:")
print(square_root_vector)

Одновимірний масив з першими 10-ма натуральними числами:
[ 1  2  3  4  5  6  7  8  9 10]

Двовимірний масив розміром 3x3, заповнений нулями:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Масив розміром 5x5, заповнений випадковими цілими числами в діапазоні від 1 до 10:
[[10  1  4  1  1]
 [10  8  4  4  2]
 [ 1  9 10  5  4]
 [ 7  9  6  9  9]
 [ 5 10  7  2  2]]

Масив розміром 4x4, заповнений випадковими дійсними числами в діапазоні від 0 до 1:
[[0.06903101 0.6996102  0.85064125 0.72092947]
 [0.55860663 0.12796591 0.06700715 0.52980573]
 [0.53865824 0.81055552 0.58941297 0.97741856]
 [0.41066267 0.99494369 0.70969863 0.35207016]]

Додавання: [13 15 11 17 18]
Віднімання: [ 3 -3 -3 -3  0]
Множення: [40 54 28 70 81]

Скалярний добуток двох векторів: 182

Результат множення двох матриць:
[[24 29 18]
 [71 43 37]]

Обернена матриця:
[[ 0.195 -0.365  0.08 ]
 [ 0.145 -0.015 -0.12 ]
 [-0.18   0.26   0.08 ]]

Транспонована матриця:
[[0.32392095 0.93339392 0.02587214 0.61620691]
 [0.58782207 0.83998431 0.94