In [28]:
import numpy as np
# 1. Створення вектора з першими 10-ма натуральними числами
vector = np.arange(1, 11)
print(vector)

[ 1  2  3  4  5  6  7  8  9 10]


In [29]:
# 2. Створення матриці розміром 3x3, заповненої нулями
matrix = np.zeros((3, 3))
print(matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [30]:
# 3. Створення масиву розміром 5x5, заповненого випадковими цілими числами в діапазоні від 1 до 10
matrix = np.random.randint(1, 11, (5, 5))
print(matrix)

[[ 4  2  6  8  9]
 [ 5 10  9  6 10]
 [ 6  8  3 10  7]
 [ 2  3  2  2  5]
 [ 2  6 10  3  2]]


In [55]:
# 4. Створення масиву розміром 4x4 з випадковими дійсними числами в діапазоні від 0 до 1
array = np.random.rand(4, 4)

print(array)

[[0.75614624 0.39702678 0.96759385 0.7389096 ]
 [0.75073965 0.8522698  0.19129638 0.88209562]
 [0.71823307 0.82313137 0.81883117 0.15911089]
 [0.60005499 0.62510939 0.55325833 0.6004019 ]]


In [33]:
# 5. Створення двох випадкових одновимірних масивів розміром 5
array1 = np.random.randint(1, 11, 5)
array2 = np.random.randint(1, 11, 5)

print(array1)
print(array2)

# Поелементне додавання
addition_result = array1 + array2
print("\nПоелементне додавання:", addition_result)

# Поелементне віднімання
subtraction_result = array1 - array2
print("Поелементне віднімання:", subtraction_result)

# Поелементне множення
multiplication_result = array1 * array2
print("Поелементне множення:", multiplication_result)

[5 8 1 4 3]
[ 1  6  8 10  8]

Поелементне додавання: [ 6 14  9 14 11]
Поелементне віднімання: [ 4  2 -7 -6 -5]
Поелементне множення: [ 5 48  8 40 24]


In [56]:
# 6. Створення двох векторів розміром 7 з довільними числами
vector1 = np.random.rand(7)
vector2 = np.random.rand(7)

print(vector1)
print(vector2)

dot_product = np.dot(vector1, vector2)
print("\nСкалярний добуток двох векторів:", dot_product)

[0.87301288 0.0082697  0.26136073 0.01940267 0.09839302 0.44751723
 0.91201969]
[0.44394285 0.75874892 0.87223289 0.06084064 0.86939519 0.96198551
 0.53255052]

Скалярний добуток двох векторів: 1.6247344195656166


In [35]:
# 7. Створення двох матриць розміром 2x2 та 2x3 з випадковими цілими числами в діапазоні від 1 до 10
matrix1 = np.random.randint(1, 11, (2, 2))
matrix2 = np.random.randint(1, 11, (2, 3))

print(matrix1)
print(matrix2)

# Перемноження матриць
matrix_product = np.dot(matrix1, matrix2)

print("\nРезультат множення двох матриць:")
print(matrix_product)

[[4 1]
 [5 5]]
[[10  3  7]
 [ 5 10  7]]

Результат множення двох матриць:
[[45 22 35]
 [75 65 70]]


In [36]:
# 8. Створення матриці розміром 3x3 з випадковими цілими числами в діапазоні від 1 до 10
matrix = np.random.randint(1, 11, (3, 3))

print(matrix)

# Перевірка, чи матриця є квадратною та невиродженою
if np.linalg.det(matrix) != 0:
    # Знаходження оберненої матриці
    inverse_matrix = np.linalg.inv(matrix)
    print("\nОбернена матриця:")
    print(inverse_matrix)
else:
    print("Матриця є виродженою, обернена матриця не існує.")

[[5 2 3]
 [1 9 1]
 [6 8 1]]

Обернена матриця:
[[-0.00813008 -0.17886179  0.20325203]
 [-0.04065041  0.10569106  0.01626016]
 [ 0.37398374  0.22764228 -0.3495935 ]]


In [38]:
# 9. Створення матриці розміром 4x4 з випадковими дійсними числами в діапазоні від 0 до 1
matrix = np.random.rand(4, 4)

print(matrix)

# Транспонування матриці
transposed_matrix = np.transpose(matrix)

print("\nТранспонована матриця:")
print(transposed_matrix)

[[0.66247536 0.18273289 0.95377135 0.28070703]
 [0.44246324 0.64014276 0.70260231 0.39907471]
 [0.02066441 0.49292822 0.03330327 0.82230565]
 [0.39896811 0.22681934 0.37161654 0.31207896]]

Транспонована матриця:
[[0.66247536 0.44246324 0.02066441 0.39896811]
 [0.18273289 0.64014276 0.49292822 0.22681934]
 [0.95377135 0.70260231 0.03330327 0.37161654]
 [0.28070703 0.39907471 0.82230565 0.31207896]]


In [40]:
# 10. Створення матриці розміром 3x4 та вектора розміром 4 з випадковими цілими числами в діапазоні від 1 до 10
matrix = np.random.randint(1, 11, (3, 4))
vector = np.random.randint(1, 11, 4)

print("Матриця:")
print(matrix)
print("\nВектор:")
print(vector)

result = np.dot(matrix, vector)

print("\nРезультат множення:")
print(result)

Матриця:
[[ 8  4  9 10]
 [ 2 10  1  4]
 [ 4  3  1  6]]

Вектор:
[5 2 5 7]

Результат множення:
[163  63  73]


In [41]:
# 11. Створення матриці розміром 2x3 та вектора розміром 3 з випадковими дійсними числами в діапазоні від 0 до 1
matrix = np.random.rand(2, 3)
vector = np.random.rand(3)

print("Матриця:")
print(matrix)
print("\nВектор:")
print(vector)

result = np.dot(matrix, vector)

print("\nРезультат:")
print(result)

Матриця:
[[0.95387199 0.70716764 0.81200557]
 [0.84891787 0.10738018 0.26178928]]

Вектор:
[0.80849457 0.21621565 0.44611345]

Результат:
[1.28634764 0.82635049]


In [43]:
# 12. Створення двох матриць розміром 2x2 з випадковими цілими числами в діапазоні від 1 до 10
matrix1 = np.random.randint(1, 11, (2, 2))
matrix2 = np.random.randint(1, 11, (2, 2))

print("Перша матриця:")
print(matrix1)
print("\nДруга матриця:")
print(matrix2)
elementwise_product = np.multiply(matrix1, matrix2)

print("\nРезультат поелементного множення")
print(elementwise_product)

Перша матриця:
[[7 7]
 [8 1]]

Друга матриця:
[[ 6  5]
 [ 5 10]]

Результат поелементного множення
[[42 35]
 [40 10]]


In [45]:
# 13. Створення двох матриць розміром 2x2 з випадковими цілими числами в діапазоні від 1 до 10
matrix1 = np.random.randint(1, 11, (2, 2))
matrix2 = np.random.randint(1, 11, (2, 2))

print("Перша матриця:")
print(matrix1)
print("\nДруга матриця:")
print(matrix2)

product = np.dot(matrix1, matrix2)

print("\nДобуток")
print(product)

Перша матриця:
[[10  2]
 [ 8  8]]

Друга матриця:
[[ 7  6]
 [10  2]]

Добуток
[[ 90  64]
 [136  64]]


In [46]:
# 14. Створення матриці розміром 5x5 з випадковими цілими числами в діапазоні від 1 до 100
matrix = np.random.randint(1, 101, (5, 5))

print(matrix)

sum_of_elements = np.sum(matrix)

print("\nСума елементів матриці:", sum_of_elements)

[[ 61  54  70  20  60]
 [ 40  68  87  63  33]
 [ 91  42  81  92  56]
 [ 61  62  90   5  40]
 [ 10  22  48  14 100]]

Сума елементів матриці: 1370


In [49]:
# 15. Створення двох матриць розміром 4x4 з випадковими цілими числами в діапазоні від 1 до 10
matrix1 = np.random.randint(1, 11, (4, 4))
matrix2 = np.random.randint(1, 11, (4, 4))

print("Перша матриця:")
print(matrix1)
print("\nДруга матриця:")
print(matrix2)

difference = matrix1 - matrix2

print("\nРізниця матриць:")
print(difference)

Перша матриця:
[[ 6  4 10  3]
 [ 4  7  1  2]
 [10  6  8  5]
 [ 6  1  6  5]]

Друга матриця:
[[ 9  1 10  7]
 [ 2  5  5  2]
 [ 3  4  5  3]
 [ 3  2 10  7]]

Різниця матриць:
[[-3  3  0 -4]
 [ 2  2 -4  0]
 [ 7  2  3  2]
 [ 3 -1 -4 -2]]


In [50]:
# 16. Створення матриці розміром 3x3 з випадковими дійсними числами в діапазоні від 0 до 1
matrix = np.random.rand(3, 3)

print("Матриця:")
print(matrix)

# Знаходження вектора-стовпчика, що містить суму елементів кожного рядка матриці
sum_of_rows = np.sum(matrix, axis=1)

print("\nСума елементів кожного рядка матриці:")
print(sum_of_rows)

Матриця:
[[0.90025681 0.47612783 0.18536421]
 [0.44565296 0.56798037 0.27379653]
 [0.28662061 0.84532336 0.86126113]]

Сума елементів кожного рядка матриці:
[1.56174885 1.28742986 1.99320511]


In [51]:
# 17. Створення матриці розміром 3x4 з довільними цілими числами
matrix = np.random.randint(1, 11, (3, 4))

print("Початкова матриця:")
print(matrix)

# Створення матриці з квадратами елементів першої матриці
squared_matrix = np.square(matrix)

print("\nМатриця з квадратами чисел:")
print(squared_matrix)

Початкова матриця:
[[4 1 3 4]
 [7 3 1 3]
 [8 7 2 2]]

Матриця з квадратами чисел:
[[16  1  9 16]
 [49  9  1  9]
 [64 49  4  4]]


In [53]:
# 18. Створення вектора розміром 4 з випадковими цілими числами в діапазоні від 1 до 50
vector = np.random.randint(1, 51, 4)

print("Вектор:")
print(vector)

# Знаходження вектора з квадратними коренями чисел
sqrt_vector = np.sqrt(vector)

print("\nВектор з квадратними коренями:")
print(sqrt_vector)

Вектор:
[ 8 20 11  2]

Вектор з квадратними коренями:
[2.82842712 4.47213595 3.31662479 1.41421356]
