In [1]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Знаходження індексів непарних чисел
indices = arr % 2 != 0

# Заміна непарних чисел на -1
arr[indices] = -1

print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [3]:
# Створення 1D-масиву
arr_1d = np.array([1, 2, 3, 4, 5, 6])

# Перетворення 1D-масиву на 2D-масив із 2 рядками
arr_2d = arr_1d.reshape(2, -1)

print("1D-масив:")
print(arr_1d)
print("\n2D-масив із 2 рядками:")
print(arr_2d)

1D-масив:
[1 2 3 4 5 6]

2D-масив із 2 рядками:
[[1 2 3]
 [4 5 6]]


In [4]:
# Створення першого масиву a
a = np.array([[1, 2, 3],
              [4, 5, 6]])

# Створення другого масиву b
b = np.array([[7, 8, 9],
              [10, 11, 12]])

# Складання масивів вертикально
result = np.vstack((a, b))

print("Масив a:")
print(a)
print("\nМасив b:")
print(b)
print("\nРезультат складання вертикально:")
print(result)

Масив a:
[[1 2 3]
 [4 5 6]]

Масив b:
[[ 7  8  9]
 [10 11 12]]

Результат складання вертикально:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [6]:
a = np.array([1, 2, 3])

output = np.concatenate((np.repeat(a, 3), np.tile(a, 3)))

print(output)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [7]:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

common_elements = np.intersect1d(a, b)

print("Спільні елементи між a і b:", common_elements)

Спільні елементи між a і b: [2 4]


In [8]:
np.random.seed(100)
a = np.random.uniform(1, 50, 20)

# Отримання індексів, які відповідають сортованим значенням у зростаючому порядку
sorted_indices = np.argsort(a)

# Вибираємо останні п'ять індексів (5 максимальних значень)
max_indices = sorted_indices[-5:]

print("Позиції перших 5 максимальних значень у масиві a:", max_indices)

Позиції перших 5 максимальних значень у масиві a: [18  7  3 10 15]


In [11]:
a = np.array([1, 2, 3, np.nan, 5, 6, 7, np.nan])

# Вилучення значень NaN з масиву
a_without_nan = a[~np.isnan(a)]

print("Масив без значень NaN:", a_without_nan)

Масив без значень NaN: [1. 2. 3. 5. 6. 7.]


In [12]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([4, 5, 6, 7, 8])

# Обчислення евклідової відстані
distance = np.linalg.norm(a - b)

print("Евклідова відстань між векторами a і b:", distance)

Евклідова відстань між векторами a і b: 6.708203932499369


In [13]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])

# Знаходимо індекси, де значення рівне 1
indices = np.where(x == 1)[0]

# Вибираємо п'ятий елемент індексів, що відповідає п'ятому повторенню числа 1
index_5th_occurrence = indices[4]

print("Індекс 5-го повторення числа 1 у масиві x:", index_5th_occurrence)

Індекс 5-го повторення числа 1 у масиві x: 8


In [14]:
np.random.seed(100)
a = np.random.randint(0, 5, 10)

# Порівняння масиву зі зсунутим на одиницю масивом, щоб знайти повторювані записи
repeated = np.concatenate(([False], a[1:] == a[:-1]))

print(repeated)

[False  True False False False False False  True  True  True]
